name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # 每12小时运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }} # 你的GitHub用户名
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
